import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header/header'
import Footer from '../../components/footer'
import LogosTags from '../../components/logosTags'
import DeveloperHeader from '@/components/developers/developerHeader'
import ListingBody from '../../components/singlelisting/listingBody'
import Features from '@/components/singlelisting/features'
import DeveloperBody from '@/components/developers/developerBody'
import AreaBody from '@/components/areas/areaBody'


export async function getStaticPaths() {
    const URL = `http://localhost:3000/areas/get-all`
    const res = await fetch(URL)
    const data = await res.json()

    const paths = data.map((area) => {
        return {
            params: {
                aid: `${area._id}`
            }
        }
    })

    return {
        paths: paths, fallback: false
    }
}

export async function getStaticProps({params}) {

    const URL = `http://localhost:3000/areas/get-area/${params.aid}`
    const res = await fetch(URL)
    const data = await res.json()

    return {
        props: {
            area: data
        }
    }
}

const AreaPage = ({area}) => {


    return (
            <>
            <Head>
                <title>Single Listing Page - Marea Capital Properties</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header />
                <DeveloperHeader 
                    name={area.areaName}
                />
                <AreaBody area={area} />


            </main>
            <Footer />
            </>
        )
}

export default AreaPage