import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Header from '../components/header/header';
import Footer from '../components/footer';
import BlogHome from '../components/blogHome';
import Testimonials from '../components/testimonialsHome';
import LogosTags from '../components/logosTags';
import Section1About from '../components/about/section1About';
import Section2About from '../components/about/section2About';
import Section3About from '../components/about/section3About';
import OurTeam from '../components/about/ourTeam';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <>
            <Header />
            <Section1About />
            <Section2About />
            <Section3About />
            <OurTeam />
            <BlogHome />
            <Testimonials />
            <LogosTags />
          </>
        </main>
      <Footer />
    </>
  )
}
