import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Header from '../components/header/header';
import Footer from '../components/footer';
import HeroSection from '../components/heroSection';
import PropertyTypes from '../components/propertyTypes';
import AboutHome from '../components/aboutHome';
import VisionHome from '../components/visionHome';
import HomeFeatured from '../components/homeFeatured';
import TopLocations from '../components/topLocations';
import MapProperties from '../components/mapProperties';
import TopDevelopers from '../components/topDevelopers';
import ServicesHome from '../components/services';
import BlogHome from '../components/blogHome';
import Testimonials from '../components/testimonialsHome';
import LogosTags from '../components/logosTags';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <>
            <Header />
            <HeroSection />
            <PropertyTypes />
            <AboutHome />
            <VisionHome />
            <HomeFeatured />
            <TopLocations />
            <MapProperties />
            <TopDevelopers />
            <ServicesHome />
            <BlogHome />
            <Testimonials />
            <LogosTags />
          </>
        </main>
      <Footer />
    </>
  )
}
