import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Header from '../components/header/header';
import Footer from '../components/footer';
import LogosTags from '../components/logosTags';
import ListingHeader from '../components/singlelisting/listingHeader';
import ListingBody from '../components/singlelisting/listingBody';


const inter = Inter({ subsets: ['latin'] })

export default function Team() {
  return (
    <>
      <Head>
        <title>Single Listing Page - Marea Capital Properties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <>
            <Header />
            <ListingHeader />
            <ListingBody />
            <LogosTags />
          </>
        </main>
      <Footer />
    </>
  )
}
