import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import Header from '../components/header/header';
import Footer from '../components/footer';
import BlogHome from '../components/blogHome';
import Testimonials from '../components/testimonialsHome';
import LogosTags from '../components/logosTags';
import HeroServices from '../components/services/HeroServices';


const inter = Inter({ subsets: ['latin'] })

export default function Services() {
  return (
    <>
      <Head>
        <title>Our Services - Marea Capital Properties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <>
            <Header />
            <HeroServices />
            <BlogHome />
            <Testimonials />
            <LogosTags />
          </>
        </main>
      <Footer />
    </>
  )
}
